<h2>Usuarios</h2>
<hr />
<p>
	<a class="btn btn-success" href="<?php echo $this->url('livraria-admin', array('controller'=>'usuarios', 'action'=>'new')) ?>">Novo</a>
</p>

<table class="table table-striped table-hover">
	<tr>
		<th width="10%">Id</th>
		<th width="40%">Nome</th>
		<th width="40%">Email</th>
		<th width="10%">Ação</th>
	</tr>
	<tbody>
		<?php foreach ($data as $categoria): ?>
			<tr>
				<td><?php echo $categoria->getId(); ?></td>
				<td><?php echo $categoria->getNome(); ?></td>
				<td><?php echo $categoria->getEmail(); ?></td>
				<td>
					<a class="glyphicon glyphicon-edit" href="<?php echo $this->url('livraria-admin-interna', array('controller'=>'usuarios', 'action'=>'edit', 'id'=>$categoria->getId())); ?>" data-toggle="tooltip" data-placement="top" title="Editar categoria"></a> 
					&nbsp;&nbsp;
					<a class="glyphicon glyphicon-trash" href="<?php echo $this->url('livraria-admin-interna', array('controller'=>'usuarios', 'action'=>'delete', 'id'=>$categoria->getId())); ?>" data-toggle="tooltip" data-placement="top" title="Excluir categoria"></a></trd>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>