<h2>Livros</h2>
<hr />
<p>
	<a class="btn btn-success" href="<?php echo $this->url('livraria-admin', array('controller'=>'livros', 'action'=>'new')) ?>">Novo</a>
</p>

<table class="table table-striped table-hover">
	<tr>
		<th width="10%">Id</th>
		<th width="30%">Nome</th>
		<th width="20%">Categoria</th>
		<th width="20%">Autor</th>
		<th width="10%">Valor</th>
		<th width="10%">Ação</th>
	</tr>
	<tbody>
		<?php foreach ($data as $livro): ?>
			<tr>
				<td><?php echo $livro->getId(); ?></td>
				<td><?php echo $livro->getNome(); ?></td>
				<td><?php echo $livro->getCategoria(); ?></td>
				<td><?php echo $livro->getAutor(); ?></td>
				<td><?php echo $livro->getValor(); ?></td>
				<td>
					<a class="glyphicon glyphicon-edit" href="<?php echo $this->url('livraria-admin-interna', array('controller'=>'livros', 'action'=>'edit', 'id'=>$livro->getId())); ?>" data-toggle="tooltip" data-placement="top" title="Editar livro"></a> 
					&nbsp;&nbsp;
					<a class="glyphicon glyphicon-trash" href="<?php echo $this->url('livraria-admin-interna', array('controller'=>'livros', 'action'=>'delete', 'id'=>$livro->getId())); ?>" data-toggle="tooltip" data-placement="top" title="Excluir livro"></a></trd>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>